name = "TickTock"
uuid = "9ff05d80-102d-5586-aa04-3a8bd1a90d20"
authors = ["cormullion <cormullion@mac.com>"]
version = "1.3.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
